


export const POST_IMAGE_REQUEST= "POST_IMAGE_REQUEST";
export const POST_IMAGE_SUCCESS = "POST_IMAGE_SUCCESS";
export const POST_IMAGE_FAILURE = "POST_IMAGE_FAILURE";


export const POST_VIDEO_REQUEST= "POST_VIDEO_REQUEST";
export const POST_VIDEO_SUCCESS = "POST_VIDEO_SUCCESS";
export const POST_VIDEO_FAILURE = "POST_VIDEO_FAILURE";