


export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST"
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS"
export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE"

export const GET_VALID_USER_REQUEST = "GET_VALID_USER_REQUEST"
export const GET_VALID_USER_SUCCESS = "GET_VALID_USER_SUCCESS"
export const GET_VALID_USER_FAILURE = "GET_VALID_USER_FAILURE"

export const ENTER_NEW_PASSWORD_REQUEST = "ENTER_NEW_PASSWORD_REQUEST"
export const ENTER_NEW_PASSWORD_SUCCESS = "ENTER_NEW_PASSWORD_SUCCESS"
export const ENTER_NEW_PASSWORD_FAILURE = "ENTER_NEW_PASSWORD_FAILURE"